server {
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/overpass_access.log;
    error_log  /var/log/nginx/overpass_error.log warn;

    location /api/interpreter {
	if ($http_origin ~ 'https?://(localhost:4283|gpx\.studio)') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        }
        proxy_pass http://localhost:80;
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_set_header Host $http_host;
    }
}